<?php
// Файл: prognozai/backend/Config/odds_market_mapper_config.php
// Назначение: Полная карта маппинга рынков коэффициентов (odds) между FonbetLeagueTextParser и betting_markets

$oddsMarketMapperConfig = [
    'football' => [
        'p1' => [
            'market_key_template' => 'football.main.1x2',
            'market_name_template_ru' => 'Исход матча 1X2 (футбол)',
            'market_name_template_en' => 'Full Time Result 1X2 (football)',
            'outcome_key' => '1',
            'outcome_display_name_template_ru' => 'П1',
            'outcome_display_name_template_en' => 'Home',
            'market_category_name_ru' => 'Основная линия',
            'market_category_name_en' => 'Main Line',
        ],
        'x' => [
            'market_key_template' => 'football.main.1x2',
            'market_name_template_ru' => 'Исход матча 1X2 (футбол)',
            'market_name_template_en' => 'Full Time Result 1X2 (football)',
            'outcome_key' => 'X',
            'outcome_display_name_template_ru' => 'X',
            'outcome_display_name_template_en' => 'Draw',
            'market_category_name_ru' => 'Основная линия',
            'market_category_name_en' => 'Main Line',
        ],
        'p2' => [
            'market_key_template' => 'football.main.1x2',
            'market_name_template_ru' => 'Исход матча 1X2 (футбол)',
            'market_name_template_en' => 'Full Time Result 1X2 (football)',
            'outcome_key' => '2',
            'outcome_display_name_template_ru' => 'П2',
            'outcome_display_name_template_en' => 'Away',
            'market_category_name_ru' => 'Основная линия',
            'market_category_name_en' => 'Main Line',
        ],
        'double_chance_1x' => [
            'market_key_template' => 'football.main.double_chance',
            'market_name_template_ru' => 'Двойной шанс',
            'market_name_template_en' => 'Double Chance',
            'outcome_key' => '1X',
            'outcome_display_name_template_ru' => '1X',
            'outcome_display_name_template_en' => '1X',
            'market_category_name_ru' => 'Двойные шансы',
            'market_category_name_en' => 'Double Chances',
        ],
        'double_chance_12' => [
            'market_key_template' => 'football.main.double_chance',
            'market_name_template_ru' => 'Двойной шанс',
            'market_name_template_en' => 'Double Chance',
            'outcome_key' => '12',
            'outcome_display_name_template_ru' => '12',
            'outcome_display_name_template_en' => '12',
            'market_category_name_ru' => 'Двойные шансы',
            'market_category_name_en' => 'Double Chances',
        ],
        'double_chance_x2' => [
            'market_key_template' => 'football.main.double_chance',
            'market_name_template_ru' => 'Двойной шанс',
            'market_name_template_en' => 'Double Chance',
            'outcome_key' => 'X2',
            'outcome_display_name_template_ru' => 'X2',
            'outcome_display_name_template_en' => 'X2',
            'market_category_name_ru' => 'Двойные шансы',
            'market_category_name_en' => 'Double Chances',
        ],
        'handicap1_value' => ['is_parameter_only' => true],
        'handicap1_coeff' => [
            'market_key_template' => 'football.handicap.main',
            'market_name_template_ru' => 'Фора 1 ({param})',
            'market_name_template_en' => 'Handicap 1 ({param})',
            'outcome_key' => 'h1',
            'outcome_display_name_template_ru' => 'Ф1 ({param})',
            'outcome_display_name_template_en' => 'Handicap 1 ({param})',
            'parameter_source_key' => 'handicap1_value',
            'market_category_name_ru' => 'Форы',
            'market_category_name_en' => 'Handicaps',
        ],
        'handicap2_value' => ['is_parameter_only' => true],
        'handicap2_coeff' => [
            'market_key_template' => 'football.handicap.main',
            'market_name_template_ru' => 'Фора 2 ({param})',
            'market_name_template_en' => 'Handicap 2 ({param})',
            'outcome_key' => 'h2',
            'outcome_display_name_template_ru' => 'Ф2 ({param})',
            'outcome_display_name_template_en' => 'Handicap 2 ({param})',
            'parameter_source_key' => 'handicap2_value',
            'market_category_name_ru' => 'Форы',
            'market_category_name_en' => 'Handicaps',
        ],
        'total_value' => ['is_parameter_only' => true],
        'total_over' => [
            'market_key_template' => 'football.total.goals',
            'market_name_template_ru' => 'Тотал голов Больше ({param})',
            'market_name_template_en' => 'Total Goals Over ({param})',
            'outcome_key' => 'over',
            'outcome_display_name_template_ru' => 'Больше ({param})',
            'outcome_display_name_template_en' => 'Over ({param})',
            'parameter_source_key' => 'total_value',
            'market_category_name_ru' => 'Тоталы',
            'market_category_name_en' => 'Totals',
        ],
        'total_under' => [
            'market_key_template' => 'football.total.goals',
            'market_name_template_ru' => 'Тотал голов Меньше ({param})',
            'market_name_template_en' => 'Total Goals Under ({param})',
            'outcome_key' => 'under',
            'outcome_display_name_template_ru' => 'Меньше ({param})',
            'outcome_display_name_template_en' => 'Under ({param})',
            'parameter_source_key' => 'total_value',
            'market_category_name_ru' => 'Тоталы',
            'market_category_name_en' => 'Totals',
        ],
        'both_yes' => [
            'market_key_template' => 'football.both_teams_to_score',
            'market_name_template_ru' => 'Обе забьют (Да/Нет)',
            'market_name_template_en' => 'Both Teams to Score (Yes/No)',
            'outcome_key' => 'yes',
            'outcome_display_name_template_ru' => 'Да',
            'outcome_display_name_template_en' => 'Yes',
            'market_category_name_ru' => 'Спец. рынки',
            'market_category_name_en' => 'Specials',
        ],
        'both_no' => [
            'market_key_template' => 'football.both_teams_to_score',
            'market_name_template_ru' => 'Обе забьют (Да/Нет)',
            'market_name_template_en' => 'Both Teams to Score (Yes/No)',
            'outcome_key' => 'no',
            'outcome_display_name_template_ru' => 'Нет',
            'outcome_display_name_template_en' => 'No',
            'market_category_name_ru' => 'Спец. рынки',
            'market_category_name_en' => 'Specials',
        ],
    ],
    'tennis' => [
        'p1' => [
            'market_key_template' => 'tennis.main.1x2',
            'market_name_template_ru' => 'Исход матча 1X2 (теннис)',
            'market_name_template_en' => 'Match Winner 1X2 (tennis)',
            'outcome_key' => '1',
            'outcome_display_name_template_ru' => 'П1',
            'outcome_display_name_template_en' => 'Player 1',
            'market_category_name_ru' => 'Основная линия',
            'market_category_name_en' => 'Main Line',
        ],
        'p2' => [
            'market_key_template' => 'tennis.main.1x2',
            'market_name_template_ru' => 'Исход матча 1X2 (теннис)',
            'market_name_template_en' => 'Match Winner 1X2 (tennis)',
            'outcome_key' => '2',
            'outcome_display_name_template_ru' => 'П2',
            'outcome_display_name_template_en' => 'Player 2',
            'market_category_name_ru' => 'Основная линия',
            'market_category_name_en' => 'Main Line',
        ],
        // --- Форы по геймам ---
        'h1_games_value' => ['is_parameter_only' => true],
        'h1_games_coeff' => [
            'market_key_template' => 'tennis.handicap.games',
            'market_name_template_ru' => 'Фора по геймам 1 ({param})',
            'market_name_template_en' => 'Games Handicap 1 ({param})',
            'outcome_key' => 'h1',
            'outcome_display_name_template_ru' => 'Ф1 ({param})',
            'outcome_display_name_template_en' => 'Handicap 1 ({param})',
            'parameter_source_key' => 'h1_games_value',
            'market_category_name_ru' => 'Форы по геймам',
            'market_category_name_en' => 'Handicaps (Games)',
        ],
        'h2_games_value' => ['is_parameter_only' => true],
        'h2_games_coeff' => [
            'market_key_template' => 'tennis.handicap.games',
            'market_name_template_ru' => 'Фора по геймам 2 ({param})',
            'market_name_template_en' => 'Games Handicap 2 ({param})',
            'outcome_key' => 'h2',
            'outcome_display_name_template_ru' => 'Ф2 ({param})',
            'outcome_display_name_template_en' => 'Handicap 2 ({param})',
            'parameter_source_key' => 'h2_games_value',
            'market_category_name_ru' => 'Форы по геймам',
            'market_category_name_en' => 'Handicaps (Games)',
        ],
        // --- Тотал по геймам ---
        'total_games_value' => ['is_parameter_only' => true],
        'total_games_over' => [
            'market_key_template' => 'tennis.total.games',
            'market_name_template_ru' => 'Тотал геймов Больше ({param})',
            'market_name_template_en' => 'Total Games Over ({param})',
            'outcome_key' => 'over',
            'outcome_display_name_template_ru' => 'Больше ({param})',
            'outcome_display_name_template_en' => 'Over ({param})',
            'parameter_source_key' => 'total_games_value',
            'market_category_name_ru' => 'Тоталы по геймам',
            'market_category_name_en' => 'Totals (Games)',
        ],
        'total_games_under' => [
            'market_key_template' => 'tennis.total.games',
            'market_name_template_ru' => 'Тотал геймов Меньше ({param})',
            'market_name_template_en' => 'Total Games Under ({param})',
            'outcome_key' => 'under',
            'outcome_display_name_template_ru' => 'Меньше ({param})',
            'outcome_display_name_template_en' => 'Under ({param})',
            'parameter_source_key' => 'total_games_value',
            'market_category_name_ru' => 'Тоталы по геймам',
            'market_category_name_en' => 'Totals (Games)',
        ],
        // --- Форы по сетам ---
        'h1_sets_value' => ['is_parameter_only' => true],
        'h1_sets_coeff' => [
            'market_key_template' => 'tennis.handicap.sets',
            'market_name_template_ru' => 'Фора по сетам 1 ({param})',
            'market_name_template_en' => 'Sets Handicap 1 ({param})',
            'outcome_key' => 'h1',
            'outcome_display_name_template_ru' => 'Ф1 ({param})',
            'outcome_display_name_template_en' => 'Handicap 1 ({param})',
            'parameter_source_key' => 'h1_sets_value',
            'market_category_name_ru' => 'Форы по сетам',
            'market_category_name_en' => 'Handicaps (Sets)',
        ],
        'h2_sets_value' => ['is_parameter_only' => true],
        'h2_sets_coeff' => [
            'market_key_template' => 'tennis.handicap.sets',
            'market_name_template_ru' => 'Фора по сетам 2 ({param})',
            'market_name_template_en' => 'Sets Handicap 2 ({param})',
            'outcome_key' => 'h2',
            'outcome_display_name_template_ru' => 'Ф2 ({param})',
            'outcome_display_name_template_en' => 'Handicap 2 ({param})',
            'parameter_source_key' => 'h2_sets_value',
            'market_category_name_ru' => 'Форы по сетам',
            'market_category_name_en' => 'Handicaps (Sets)',
        ],
        // --- Тоталы по сетам ---
        'total_sets_value' => ['is_parameter_only' => true],
        'total_sets_over' => [
            'market_key_template' => 'tennis.total.sets',
            'market_name_template_ru' => 'Тотал сетов Больше ({param})',
            'market_name_template_en' => 'Total Sets Over ({param})',
            'outcome_key' => 'over',
            'outcome_display_name_template_ru' => 'Больше ({param})',
            'outcome_display_name_template_en' => 'Over ({param})',
            'parameter_source_key' => 'total_sets_value',
            'market_category_name_ru' => 'Тоталы по сетам',
            'market_category_name_en' => 'Totals (Sets)',
        ],
        'total_sets_under' => [
            'market_key_template' => 'tennis.total.sets',
            'market_name_template_ru' => 'Тотал сетов Меньше ({param})',
            'market_name_template_en' => 'Total Sets Under ({param})',
            'outcome_key' => 'under',
            'outcome_display_name_template_ru' => 'Меньше ({param})',
            'outcome_display_name_template_en' => 'Under ({param})',
            'parameter_source_key' => 'total_sets_value',
            'market_category_name_ru' => 'Тоталы по сетам',
            'market_category_name_en' => 'Totals (Sets)',
        ],
    ],
];

return $oddsMarketMapperConfig;
